[package]
name = "crypto-currency-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
k256 = { version = "0.13", features = ["ecdsa", "pkcs8"] }


ripple-address-codec = "*"
hex = "*"
ring = "*"
base-x = "*"
ripemd = "*"
